add_newline = false
[line_break]
disabled = true
[character]     
vicmd_symbol = "->"

[username]
disabled = false
show_always = true
style_user = "blue"

[directory]
style = "green"

[git_branch]
style = "red"

[package]
symbol = ""
[dotnet]
symbol="dotnet "
[nodejs]
symbol="nodejs "
[php]
symbol="php "
[python]
symbol="python "

[cmd_duration]
min_time = 0
format = "took "

[time]
disabled = true
style = "white"
